RC.Website.FileManage/Controllers/AdminController.cs
using System.Text.RegularExpressions;
using System.Web.Mvc;
using RC.Website.FileManage.Attribute.Authorize;

namespace RC.Website.FileManage.Controllers
{
    [AdminAuthorize]
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FileManage()
        {
            return View();
        }

        public ActionResult Account()
        {
            return View("~/views/admin/AccountList.cshtml");
        }

        public ActionResult Document()
        {
            var url = "";
            if (ControllerContext.RequestContext.HttpContext.Request.Url != null)
            {
                url = ControllerContext.RequestContext.HttpContext.Request.Url.ToString();
                url = new Regex(
                    "(?i)http://([\\s\\S]*?)/",
                    RegexOptions.CultureInvariant
                    | RegexOptions.Compiled
                ).Match(url).Value;
            }

            ViewBag.Url = url;
            return View();
        }
    }
}

RC.Website.FileManage/Controllers/FileController.cs
using System.Data.SqlClient;
using System.IO;
using System.Web.Mvc;
using RC.FileManage;

namespace RC.Website.FileManage.Controllers
{
    public class FileController : Controller
    {
        /// <summary>
        ///     预览文件
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Preview(string id)
        {
            if (string.IsNullOrEmpty(id)) return Content("抱歉，参数错误");

            var file = SqlHelper.Query("SELECT [fullpath],extension  FROM  [RC_File_FileUpload] WHERE guid=@guid",new[] {new SqlParameter {ParameterName = "guid", Value = id}});
            if (file.Rows.Count == 0) return Content("抱歉，文件记录不存在");

            var filepath = file.Rows[0]["fullpath"].ToStr();
            var extension = file.Rows[0]["extension"].ToStr();
            if (!System.IO.File.Exists(filepath)) return Content("抱歉，文件不存在");

            switch (extension)
            {
                #region 脚本文件

                case ".js":
                    return JavaScript(System.IO.File.ReadAllText(filepath));

                #endregion

                #region 文本文件

                case ".config":
                case ".cs":
                case ".css":
                case ".txt":
                case ".suo":
                case ".sln":
                case ".asmx":
                case ".aspx":
                    return File(filepath, "text/plain");

                #endregion

                #region 图片预览

                case ".gif":
                case ".jpg":
                case ".png":
                    return File(filepath, "image/jpeg");

                #endregion

                default:
                    return File(filepath, "text/plain", Path.GetFileName(filepath));
            }
        }
    }
}

RC.Website.FileManage/Controllers/FileManageController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Web.Mvc;
using RC.FileManage;
using RC.Website.FileManage.Attribute.Authorize;

namespace RC.Website.FileManage.Controllers
{
    [AdminAuthorize]
    public class FileManageController : Controller
    {
        public ActionResult GetRoot()
        {
            var dt = SqlHelper.Query(@"SELECT  guid,name,fullpath
            FROM   [RC_File_FileUpload]
            WHERE   isroot = 1 Order By creationtime DESC");
            var list = new List<string>();
            for (var i = 0; i < dt.Rows.Count; i++)
            {
                var row = dt.Rows[i];
                list.Add("{\"id\":\"" + row["guid"] + "\",\"text\":\"" + row["name"] +"\",\"children\":[],\"state\":\"closed\"}");
            } 
            return new ContentResult
            {
                Content = "[{\"id\":1,\"text\":\"所有目录\",\"children\":[" + string.Join(",", list.ToArray()) + "]}]"
            };
        }

        public ActionResult GetChildren()
        {
            var id = RequestHelper.GetParm("id");
            var dt = SqlHelper.Query(
                @" SELECT guid, name,(SELECT COUNT(*) FROM RC_File_FileUpload WHERE parentpath=u.fullpath)cnt
                                                     FROM   RC_File_FileUpload u
                                                     WHERE  parentpath IN ( SELECT  fullpath FROM    RC_File_FileUpload WHERE   guid = @guid )
                                                     AND Type='dir'
                                                     ORDER BY creationtime DESC",
                new[] { new SqlParameter { ParameterName = "guid", Value = id } });
            var list = new List<string>();
            for (var i = 0; i < dt.Rows.Count; i++)
            {
                var row = dt.Rows[i];
                if (row["cnt"].ToInt() > 0)
                    list.Add("{\"id\":\"" + row["guid"] + "\",\"text\":\"" + row["name"] +
                             "\",\"children\":[],\"state\":\"closed\",\"iconCls\":\"tree-folder\"}");
                else
                    list.Add("{\"id\":\"" + row["guid"] + "\",\"text\":\"" + row["name"] +
                             "\",\"children\":[],\"state\":\"open\",\"iconCls\":\"tree-folder\"}");
            }

            return new ContentResult { Content = "[" + string.Join(",", list.ToArray()) + "]" };
        }

        public ActionResult GetFile(string guid, int page = 1, int rows = 20, string searchType = "", string keyword = "")
        {
            var conditions = new Dictionary<string, string>();
            if (searchType.IsNotEmpty() && keyword.IsNotEmpty()) conditions.Add(searchType, keyword);
            var request = new PageRequest
            {
                CurrentPage = page,
                PageSize = rows,
                Conditions = conditions,
                Sorts = new Dictionary<string, string> { { "creationtime", "DESC" } }
            };
            var orderBy = new List<string>();
            foreach (var pair in request.Sorts) orderBy.Add(pair.Key + " " + pair.Value);

            var dataSql = string.Format(
                @"SELECT * FROM (SELECT *,ROW_NUMBER() OVER(ORDER BY {0}) AS RowNum FROM RC_File_FileUpload WHERE parentpath IN ( SELECT  fullpath
            FROM    RC_File_FileUpload
            WHERE   guid = @guid)  AND type='file' ", string.Join(",", orderBy.ToArray()));

            const string countSql = @"SELECT COUNT(*) FROM RC_File_FileUpload WHERE  parentpath IN ( SELECT  fullpath
            FROM    RC_File_FileUpload
            WHERE   guid = @guid) AND type='file' ";
            var parms = new List<SqlParameter>();
            var whereSql = "";
            parms.Add(new SqlParameter { ParameterName = "guid", Value = guid });

            if (request.Conditions.Count > 0)
                foreach (var condition in request.Conditions)
                    switch (condition.Key)
                    {
                        default:
                            if (!condition.Value.IsEmpty())
                            {
                                whereSql += string.Format(" AND {0} like '%'+@{0}+'%' ", condition.Key);
                                parms.Add(new SqlParameter { ParameterName = condition.Key, Value = condition.Value });
                            }

                            break;
                    }
            dataSql += string.Format("{0})temp WHERE RowNum BETWEEN {1} AND {2}  ORDER BY temp.RowNum ASC ", whereSql,
                request.Begin, request.End);

            var response = new PageResponse
            {
                Data = SqlHelper.Query(dataSql, parms.ToArray()),
                Total = SqlHelper.ExecuteScalar(countSql + whereSql, parms.ToArray()).ToInt()
            };
            return new ContentResult { Content = response.ToJson() };
        }

        public ActionResult DelFile(string id)
        {
            var result = new AjaxResult();
            try
            {
                SqlHelper.ExecuteNonQuery("DELETE FROM [RC_File_FileUpload] WHERE Guid=@Guid", new[] { new SqlParameter { ParameterName = "Guid", Value = id } });
                result.IsSucess = true;
                result.Body = "";
            }
            catch (Exception ex)
            {
                result.IsSucess = false;
                result.Body = ex.Message;
            }

            return new ContentResult { Content = result.ToJson() };
        }
    }
}

RC.Website.FileManage/Views/Admin/Document.cshtml
@{
    ViewBag.Title = "接入文档";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body { font-size: 14px; }
    h3 { padding: 0; margin: 0; font-size: 16px; }
    hr { border: 1px solid #e3e3e3; }
    ul { padding: 5px 10px; margin: 0; }
    li { list-style: none; line-height: 1.6; }
    .keyword { color: red; display: inline-block; margin: 0 3px; }
    pre { display: block; padding: 9.5px; margin: 0 0 10px; font-size: 13px; line-height: 1.42857143; color: #333; word-break: break-all; word-wrap: break-word; background-color: #f5f5f5; border: 1px solid #ccc; border-radius: 4px; }
    .panel-fit body { overflow: auto !important; }
</style>
<div style="padding: 10px">
    <h3>
        一、上传文件</h3>
    <hr />
    <ul>
        <li>第1步：申请应用：向管理员申请接入应用的<span class="keyword">Appkey</span>和<span class="keyword">AppSecret</span>。</li>
        <li>第2步：接口调用 <a href="/Uploadfiles/RC.Software.FileManager.rar" target="_blank">下载客户端调用示例</a></li>
        <li>
            <ul>
                <li>1.接口地址：<span class="keyword"><a href="@(ViewBag.Url + "UploadFile.asmx")"target="_blank">@(ViewBag.Url + "UploadFile.asmx")</a></span>，将接口地址添加服务引用到你的项目。</li>
                <li>2.调用方式：
                    <pre>
/// &lt;summary&gt;
/// 上传文件
/// &lt;/summary&gt;
/// &lt;param name=&quot;url&quot;&gt;接口路径&lt;/param&gt;
/// &lt;param name=&quot;appkey&quot;&gt;由系统颁发&lt;/param&gt;
/// &lt;param name=&quot;appsecret&quot;&gt;由系统颁发&lt;/param&gt;
/// &lt;param name=&quot;filepath&quot;&gt;上传文件全路径&lt;/param&gt;
/// &lt;param name=&quot;tableName&quot;&gt;业务关联表&lt;/param&gt;
/// &lt;param name=&quot;tableKeyId&quot;&gt;业务表主键&lt;/param&gt;
/// &lt;returns&gt;&lt;/returns&gt;
protected string Uploadfile(string url, string appkey, string appsecret, string filepath, string tableName, string tableKeyId)
{
    var service = new UploadFile(); //webservice引用
    service.Url = url;
    var timestamp = DateTime.Now.ToString(&quot;yyyy-MM-dd HH:mm:ss&quot;);
    var file = new FileInfo(txtFilepath.Text.Trim());
    var bytes = new byte[file.Length];
    using (var stream = file.OpenRead())
    {
        stream.Read(bytes, 0, Convert.ToInt32(file.Length));
    }

    var dic = new Dictionary&lt;string, string&gt; { { &quot;appkey&quot;, appkey }, { &quot;timestamp&quot;, timestamp } };
    var sign = SignRequest(dic, appsecret);
    var result = service.Upload(appkey, timestamp, sign, bytes, file.Name, tableName, tableKeyId);
    return result;
}
</pre>
                </li>
                <li>3.签名算法：
                    <pre>
/// &lt;summary&gt;
/// 接口签名算法
/// &lt;/summary&gt;
/// &lt;param name=&quot;parameters&quot;&gt;请求参数&lt;/param&gt;
/// &lt;param name=&quot;secret&quot;&gt;由清山.NET市场信息部颁发&lt;/param&gt;
/// &lt;returns&gt;&lt;/returns&gt;
public static string <span class="keyword">SignRequest</span>(IDictionary&lt;string, string&gt; parameters, string secret)
{
    // 第一步：把字典按Key的字母顺序排序
    IDictionary&lt;string, string&gt; sortedParams =
        new SortedDictionary&lt;string, string&gt;(parameters, StringComparer.Ordinal);
    var dem = sortedParams.GetEnumerator();

    // 第二步：把所有参数名和参数值串在一起
    var query = new System.Text.StringBuilder();

    while (dem.MoveNext())
    {
        var key = dem.Current.Key;
        var value = dem.Current.Value;
        if (!string.IsNullOrEmpty(key) &amp;&amp; !string.IsNullOrEmpty(value)) query.Append(key).Append(value);
    }

    // 第三步：使用MD5/HMAC加密
    query.Append(secret);
    var md5 = System.Security.Cryptography.MD5.Create();
    var bytes = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(query.ToString()));


    // 第四步：把二进制转化为大写的十六进制
    var result = new System.Text.StringBuilder();
    for (var i = 0; i &lt; bytes.Length; i++)
        result.Append(bytes[i].ToString(&quot;X2&quot;));

    return result.ToString();
}
</pre>
                </li>
                <li>4.返回结果
                    <pre>
{"IsSuccess":true,"Body":"97127bdee07648f79d5c0eefe0fdc965"}
IsSuccess=true时，上传成功，Body为上传后文件的guid（取文件时需要）。
IsSuccess=false时，上传失败，Body为上传失败原因。
</pre>
                </li>
            </ul>
        </li>
    </ul>
    <h3>
        二、读取(下载)文件</h3>
    <hr />
    <ul>
        <li>访问地址 <span class="keyword">@(ViewBag.Url + "File/Preview/[guid]")</span>，如：<a href="@(ViewBag.Url + "File/Preview/97127bdee07648f79d5c0eefe0fdc965")" target="_blank">@(ViewBag.Url + "File/Preview/97127bdee07648f79d5c0eefe0fdc965")</a></li></ul>
</div>

RC.Website.FileManage/Views/Admin/FileManage.cshtml
@{
    ViewBag.Title = "接入文档";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .panel-header { border-top: 0; border-left: 0; }
    .tree-folder { background: url(/Scripts/jquery-easyui-1.5.5.7/themes/default/images/tree_icons.png) no-repeat -208px 0 !important; }
    .ico { vertical-align: middle; margin-right: 3px; }
    .btnoper { width: 16px; height: 16px; display: block; }
    .btnoper-txt { display: inline-block; margin-left: 18px; color: black; }
</style>
<!--左侧部分-->
<div id="west" data-options="region:'west',split:true,title:'目录导航'" style="padding: 0px;
    border-left: 0; border-top: 0; border-bottom: 0; width: 250px;">
    <ul id="fileTree" data-options="lines:true">
    </ul>
    <script type="text/javascript">
        var _curGuid = "";
        $('#fileTree').tree({
            url: '@Url.Action("GetRoot", "FileManage")',
            onBeforeExpand: function (node, param) {
                $(this).tree('options').url = "@Url.Action("GetChildren", "FileManage")?state=open&id=" + node.id; 
            },
            onSelect: function (node, param) {
                _curGuid = node.id;
                Search();
            }
        });
        function Search() {
            $('#table').datagrid('options').url = '@Url.Action("GetFile", "FileManage")?_t=' +
                new Date().getTime() +
                '&guid=' +_curGuid +
                '&searchType=' +$("[name='searchType']").val() +
                '&keyword=' +escape($("[name='keyword']").val());
            Reload();
        }

        //刷新 
        function Reload() {
            $('#table').datagrid('reload');
            $('#table').datagrid('clearSelections');
        }

        //自适应缩放
        function customResize() {
            var width = $("#file-right").width();
            var height = $(window).height()-$("#myToolbar").height()+30;
            $('#table').datagrid('resize', { width: width, height: height });
        }
    </script>
</div>
<!--右侧部分-->
<div data-options="region:'center'" style="border-top: 0; border-bottom: 0" id="file-right">
    <div id="myToolbar" class="datagrid-toolbar">
        <ul class="datagridMenu">
            <li>
                <select class="easyui-combobox" name="searchType" style="width: 110px;">
                    <option value='name'>文件名</option>
                    <option value='extension'>后缀名</option>
                </select>
            </li>
            <li>
                <input type="text" id="keyword" style="width: 300px;" name="keyword" class="easyui-textbox" />
                <script type="text/javascript">

                    $(function () {
                        var defaultKeyword = "输入关键字以进行搜索(支持回车即搜索)";
                        $("[name='keyword']").prev().val(defaultKeyword);
                        //获取焦点
                        $("[name='keyword']").prev().focus(function () {
                            if ($.trim($(this).val()) == defaultKeyword) {
                                $(this).val("");
                            }
                        });
                        //失去焦点
                        $("[name='keyword']").prev().blur(function () {
                            if ($.trim($(this).val()) == "") {
                                $(this).val(defaultKeyword);
                            }
                        });
                        $("[name='keyword']").prev().bind('keydown', function (e) {
                            var key = e.which;
                            if (key == 13) {
                                e.preventDefault();
                                $(this).blur(); //失去焦点，给隐藏域赋值
                                Search();
                            }
                        });
                    });
                </script>
            </li>
            <li><a onclick=" Search(); " href="javascript:void(0)" plain="true" class="easyui-linkbutton"
                data-options="iconCls:'icon-search'" title="搜索">搜索</a> </li>
            <li><a onclick=" Delete(); " href="javascript:void(0)" plain="true" class="easyui-linkbutton"
                data-options="iconCls:'icon-remove'" title="删除">删除</a> </li>
            <li><a onclick=" Reload(); " href="javascript:void(0)" plain="true" class="easyui-linkbutton"
                data-options="iconCls:'icon-reload'" title="刷新">刷新</a> </li>
        </ul>
        <div style="clear: both">
        </div>
    </div>
    <table id="table" class="easyui-datagrid" data-options="
				title: '',
                method: 'post',
                singleSelect:true,
				rownumbers: false, 
				idField: 'Id',
                fitColumns:true,
				treeField: 'Title',
                columns:[[ 
              
                 {field:'name',title:'名称',width:120,align:'left',formatter: function(value,row,index){return initname(row.value,row,index);}},
                 {field:'fullpath',title:'路径',width:300,align:'left',formatter: function(value,row,index){return initfullpath(row.value,row,index);}},
                 {field:'extension',title:'扩展名',width:60,align:'left',formatter: function(value,row,index){return initextension(row.value,row,index);}},
                 {field:'length',title:'大小',width:60,align:'left',formatter: function(value,row,index){return initlength(row.value,row,index);}},
                 {field:'creationtime',title:'创建时间',width:120,align:'left',formatter: function(value,row,index){return initcreationtime(row.value,row,index);}},
                 {field:'oprate',title:'操作',width:60,align:'left',formatter: function(value,row,index){return initOperate(row.value,row,index);}}
               
                ]],
                toolbar:'#myToolbar',
                pagination:true,
                onClickRow: onClickRow,

                pageSize:20, 
                border:0
			">
    </table>
    <script type="text/javascript">
        var editId = "";

        //行单击事件
        function onClickRow(index, row) {
            editId = row.guid;
        }

        //删除
        function Delete() {
            if (editId <= 0) {
                rc.msg.alertErrorMsg("请选择要操作的数据行");
                return;
            }
            rc.msg.confirm("确定要删除该记录吗？",
                function () {
                    rc.loading.add();
                    rc.ajax.post('@Url.Action("DelFile", "FileManage")',
                        {
                            data: {
                                id: editId
                            },
                            success: function (response) {
                                rc.loading.remove();
                                if (response.IsSucess) {
                                    Reload();
                                     
                                } else {
                                    rc.msg.alertErrorMsg(response.Body);
                                }
                            }
                        });
                });
        }

        function initname(value, row, index) {
            var ico = "";
            switch (row.extension.replace(".", "").toLowerCase()) {
                case "cs":
                case "txt":
                case "doc":
                case "docx":
                case "xls":
                case "xlsx":
                case "exe":
                case "ppt":
                case "dll":
                case "pdf":
                case "pptx":
                case "zip":
                case "rar":
                case "jpg":
                case "html":
                case "cshtml":
                case "config":
                case "aspx":
                case "png":
                    ico = "<img class='ico' src='/Content/images/ext/" + row.extension.replace(".", "").toLowerCase() + ".png' />";
                    break;
                default:
                    ico = "<img class='ico' src='/Content/images/ext/default.png' />";
                    break;
            }
            return ico + row.name;
        }

        function initfullpath(value, row, index) {
            return row.fullpath;
        }

        function initextension(value, row, index) {
            return row.extension;
        }
        
        var KBCount = 1024;
        var MBCount = KBCount * 1024;
        var GBCount = MBCount * 1024;
        var TBCount = GBCount * 1024;
        function initlength(value, row, index) {
            var size = row.length; 
            if (KBCount > size){return size+ "B";}
            if (MBCount > size){return (size / KBCount).toFixed(2) + "KB";}
            if (GBCount > size){return (size / MBCount).toFixed(2) + "MB";}
            if (TBCount > size){return (size / GBCount) .toFixed(2)+ "GB";}
            return (size / TBCount) .toFixed(2)+ "TB";
        }

        function initcreationtime(value, row, index) {
            return fixJsonDate(row.creationtime,"yyyy-MM-dd HH:mm"); 
        }
        function initOperate(value, row, index) {
            return "<a plain='true' class=''  href='@Url.Action("Preview", "File")/"+row.guid+"' target='_blank' title='预览'><span class='btnoper icons-application_put'><span class='btnoper-txt'>预览</span></a>";
        }
        function  fixJsonDate  (jsonDate, format) {// 发现实体转换的日期会多了8个小时，使用该方法会修正这8个小时
            if (RegExp(/\d{4}-\d+-\d+\s+\d+:\d+:\d+/).test(jsonDate)) {
                return jsonDate;
            }
            var date = null;
            if (RegExp(/\d{4}\/\d+\/\d+\s+\d+:\d+:\d+/).test(jsonDate)) {
                date = new Date(jsonDate);
            } else {
                if (jsonDate) {
                    var strDate = jsonDate.replace("/Date(", "").replace(")/", "");
                    try {
                        date = new Date(parseInt(strDate) - (8 * 3600 * 1000));
                    } catch(ex) {
                    }
                }
            }
            if (!date) {
                return "";
            }
            date = { year: date.getFullYear(), month: date.getMonth() + 1, day: date.getDate(), hour: date.getHours(), minutes: date.getMinutes() };
            switch (format) {
            case '-':
                return date.year + '-' + fixTime(date.month) + '-' + fixTime(date.day);
            case 'zh':
                return date.year + '年' + fixTime(date.month) + '月' + fixTime(date.day) + '日';
            default:
                return date.year + '-' + fixTime(date.month) + '-' + fixTime(date.day) + ' ' + fixTime(date.hour) + ':' + fixTime(date.minutes);
            }
            function fixTime(value) {
                return value.toString().length > 1 ? value : "0" + value;
            }
        }
    </script>
</div>

RC.Website.FileManage/Views/Admin/Index.cshtml
@using RC.FileManage
@{
    ViewBag.Title = "清山.NET上传文件管理系统";
    Layout = "~/Views/Shared/_LayoutNull.cshtml";
}
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="/Scripts/jquery-easyui-1.5.5.7/themes/default/easyui.css" rel="stylesheet"
        type="text/css" />
    <link href="/Scripts/jquery-easyui-1.5.5.7/themes/icon.css" rel="stylesheet" type="text/css" />
    <link href="/Scripts/jquery-easyui-1.5.5.7/themes/icons-custom.css" rel="stylesheet"
        type="text/css" />
    <script src="/Scripts/jquery-easyui-1.5.5.7/jquery.min.js" type="text/javascript"></script>
    <script src="/Scripts/jquery-easyui-1.5.5.7/jquery.easyui.min.js" type="text/javascript"></script>
    <script src="/Scripts/jquery-easyui-1.5.5.7/jquery.ezsyui.plugin.tab.js" type="text/javascript"></script>
    <style type="text/css">
        .btn-guide { width: 96%; text-align: left; }
        .logo { font-size: 16px; font-weight: bold; color: #444; line-height: 39px; text-shadow: 0 0 10px #95b8e7; letter-spacing: 5px; display: block; margin-left: 10px; }
        .titlebar { background: #e6efff; height: 40px; border-top: 0px; background-color: #E0ECFF; background: -webkit-linear-gradient(top,#EFF5FF 0,#E0ECFF 100%); background: -moz-linear-gradient(top,#EFF5FF 0,#E0ECFF 100%); background: -o-linear-gradient(top,#EFF5FF 0,#E0ECFF 100%); background: linear-gradient(to bottom,#EFF5FF 0,#E0ECFF 100%); background-repeat: repeat-x; }
        .login-status { float: right; position: absolute; top: 5px; right: 15px; }
        .btn-logout { display: inline-block; margin-left: 10px; text-decoration: none; border: 1px solid #cccccc; padding: 1px 5px; font-size: 12px; border-radius: 3px; color: #333; }
    </style>
</head>
<body class="easyui-layout">
    <!--顶部导航-->
    <div data-options="region:'north',split:false" class="titlebar">
        <span class="logo">@ViewBag.Title</span><div class="login-status">
            你好，@Session["CurrentUser"].ToStr() 
            <a href="@Url.Action("Logout", "Home")" class="easyui-linkbutton" data-options="plain:true,iconCls:'icons-door_in'"
             >退出</a>
            </div>
    </div>
    <!--左侧导航-->
    <div id="west" data-options="region:'west',split:true,title:'控制面板'" style="padding: 0px;
        width: 200px;">
        <div id="secondMenuguide" class="easyui-accordion" data-options="fit:true,border:false">
            <div id="aa" class="easyui-accordion" style="height: 160px; width: 300px;">
                <div title="" data-options="iconCls:'icon-ok'" style="overflow: auto; padding: 10px;">
                    @*应用管理*@ <a href="javascript:addTab('应用管理','@Url.Action("AccountList", "Account")')" data-options="plain:true,iconCls:'icons-application_get'"
                        title="应用管理" class="easyui-linkbutton btn-guide">应用管理 </a>@*文件管理*@ <a href="javascript:addTab('文件管理','@Url.Action("FileManage", "Admin")')"
                            class="easyui-linkbutton btn-guide" data-options="plain:true,iconCls:'icons-drive'">
                            文件管理</a>@*接入文档*@ <a href="javascript:addTab('接入文档','@Url.Action("Document", "Admin")')" class="easyui-linkbutton btn-guide"
                                data-options="plain:true,iconCls:'icons-doc_offlice'">开发文档</a>
                </div>
            </div>
        </div>
    </div>
    <!--右侧部分-->
    <div data-options="region:'center'">
        <div id="tt" class="easyui-tabs" fit="true" border="false" plain="true" data-options="tools:'#tab-tools'"
            style="height: 100%; width: 100%;">
        </div>
        <div id="tab-tools">
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icons-cross'"
                onclick="removePanel()">关闭</a>
        </div>
    </div>
    <!--底部部分-->
    <div region="south" data-options="split:false" style="height: 30px;">
        <div class="footer" style="color: #444; padding: 6px; text-align: center;">
            <a href="http://www.miitbeian.gov.cn/" style="color: gray; text-decoration: none;
                font-size: 12px" target="_blank">Copyright &#169; 2018 清山.NET All Rights Reserved.
            </a>
        </div>
    </div>
    <script type="text/javascript">
        $(function() {
            addTab("开发文档", "@Url.Action("Document", "Admin")");

            
            //双击关闭Tab 
//            $(".tabs li").live();.dblclick(function() {
//                //alert($(this).text());
//                $('#tt').tabs("close", $(this).text()); 
//            });
        });

        function removePanel(){
            var tab = $('#tt').tabs('getSelected');
            if (tab){
                var index = $('#tt').tabs('getTabIndex', tab);
                $('#tt').tabs('close', index);
            }
        }

        function addTab(title, url) {
            if ($('#tt').tabs('exists', title)) {
                $('#tt').tabs('select', title);
                var allTabs = $('#tt').tabs('tabs');
                $.each(allTabs,
                    function() {
                        var ctab = this;
                        var opt = ctab.panel('options');
                        if (opt.title == title) {
                            //刷新Tab页
                            var newContent = '<iframe scrolling="auto" frameborder="0"  src="' +
                                url +
                                '" style="width:100%;height:100%;"></iframe>';
                            $('#tt').tabs('update',
                                {
                                    tab: ctab,
                                    options: {
                                        title: title,
                                        content: newContent
                                    }
                                });
                        }
                    });
            } else {
                var content = '<iframe scrolling="auto" frameborder="0"  src="' +
                    url +
                    '" style="width:100%;height:100%;"></iframe>';
                $('#tt').tabs('add',
                    {
                        title: title,
                        content: content,
                        height: '400px',
                        closable: true
                    });
            }
        }

        function closeTab() {
            var tab = $('#tt').tabs('getSelected');
            if (tab) {
                var index = $('#tt').tabs('getTabIndex', tab);
                $('#tt').tabs('close', index);
            }
        }
    </script>
</body>
</html>